#!/bin/bash

zenity --forms --title="Pesquisador de processos" \
        --add-entry="Qual o processo você deseja pesquisar?"
        if [ $processo == $(cat arq.txt | grep $processo) ]; then
        ps aux | grep $processo
        else
              zenity --info --text="Processo inexistente!"
fi

processo=$(cut -f 1)
